var tree = [["Icecave",,"",
                [["Archer",,"",
                [["Configuration","Icecave\/Archer\/Configuration.html","",
                [["ComposerConfigurationReader","Icecave\/Archer\/Configuration\/ComposerConfigurationReader.html","",
                [        ]],["ConfigurationFileFinder","Icecave\/Archer\/Configuration\/ConfigurationFileFinder.html","",
                [        ]],["PHPConfigurationReader","Icecave\/Archer\/Configuration\/PHPConfigurationReader.html","",
                [        ]]        ]],["Console","Icecave\/Archer\/Console.html","",
                [["Command","Icecave\/Archer\/Console\/Command.html","",
                [["Internal","Icecave\/Archer\/Console\/Command\/Internal.html","",
                [["AbstractInternalCommand","Icecave\/Archer\/Console\/Command\/Internal\/AbstractInternalCommand.html"," < Command",
                [        ]],["UpdateBinariesCommand","Icecave\/Archer\/Console\/Command\/Internal\/UpdateBinariesCommand.html"," < AbstractInternalCommand",
                [        ]]        ]],["Travis","Icecave\/Archer\/Console\/Command\/Travis.html","",
                [["AbstractTravisCommand","Icecave\/Archer\/Console\/Command\/Travis\/AbstractTravisCommand.html"," < Command",
                [        ]],["BuildCommand","Icecave\/Archer\/Console\/Command\/Travis\/BuildCommand.html"," < AbstractTravisCommand",
                [        ]]        ]],["AbstractPHPUnitCommand","Icecave\/Archer\/Console\/Command\/AbstractPHPUnitCommand.html"," < Command",
                [        ]],["CoverageCommand","Icecave\/Archer\/Console\/Command\/CoverageCommand.html"," < AbstractPHPUnitCommand",
                [        ]],["DocumentationCommand","Icecave\/Archer\/Console\/Command\/DocumentationCommand.html"," < Command",
                [        ]],["TestCommand","Icecave\/Archer\/Console\/Command\/TestCommand.html"," < AbstractPHPUnitCommand",
                [        ]],["UpdateCommand","Icecave\/Archer\/Console\/Command\/UpdateCommand.html"," < Command",
                [        ]]        ]],["Helper","Icecave\/Archer\/Console\/Helper.html","",
                [["HiddenInputHelper","Icecave\/Archer\/Console\/Helper\/HiddenInputHelper.html"," < Helper",
                [        ]]        ]],["Application","Icecave\/Archer\/Console\/Application.html"," < Application",
                [        ]]        ]],["Coveralls","Icecave\/Archer\/Coveralls.html","",
                [["CoverallsClient","Icecave\/Archer\/Coveralls\/CoverallsClient.html","",
                [        ]]        ]],["Documentation","Icecave\/Archer\/Documentation.html","",
                [["DocumentationGenerator","Icecave\/Archer\/Documentation\/DocumentationGenerator.html","",
                [        ]]        ]],["FileSystem","Icecave\/Archer\/FileSystem.html","",
                [["Exception","Icecave\/Archer\/FileSystem\/Exception.html","",
                [["ReadException","Icecave\/Archer\/FileSystem\/Exception\/ReadException.html"," < RuntimeException",
                [        ]],["WriteException","Icecave\/Archer\/FileSystem\/Exception\/WriteException.html"," < RuntimeException",
                [        ]]        ]],["FileSystem","Icecave\/Archer\/FileSystem\/FileSystem.html","",
                [        ]]        ]],["Git","Icecave\/Archer\/Git.html","",
                [["GitConfigReader","Icecave\/Archer\/Git\/GitConfigReader.html","",
                [        ]],["GitConfigReaderFactory","Icecave\/Archer\/Git\/GitConfigReaderFactory.html","",
                [        ]],["GitDotFilesManager","Icecave\/Archer\/Git\/GitDotFilesManager.html","",
                [        ]]        ]],["GitHub","Icecave\/Archer\/GitHub.html","",
                [["GitHubClient","Icecave\/Archer\/GitHub\/GitHubClient.html","",
                [        ]]        ]],["Process","Icecave\/Archer\/Process.html","",
                [["PHPUnitExecutableFinder","Icecave\/Archer\/Process\/PHPUnitExecutableFinder.html","",
                [        ]],["ProcessFactory","Icecave\/Archer\/Process\/ProcessFactory.html","",
                [        ]]        ]],["Support","Icecave\/Archer\/Support.html","",
                [["Composer",,"",
                [["Package",,"",
                [["LinkConstraint","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint.html","",
                [["EmptyConstraint","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint\/EmptyConstraint.html","",
                [        ]],["LinkConstraintInterface","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint\/LinkConstraintInterface.html","",
                [        ]],["MultiConstraint","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint\/MultiConstraint.html","",
                [        ]],["SpecificConstraint","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint\/SpecificConstraint.html","",
                [        ]],["VersionConstraint","Icecave\/Archer\/Support\/Composer\/Package\/LinkConstraint\/VersionConstraint.html"," < SpecificConstraint",
                [        ]]        ]],["Version","Icecave\/Archer\/Support\/Composer\/Package\/Version.html","",
                [["VersionParser","Icecave\/Archer\/Support\/Composer\/Package\/Version\/VersionParser.html","",
                [        ]]        ]]        ]]        ]],["Liftoff","Icecave\/Archer\/Support\/Liftoff.html","",
                [["Exception","Icecave\/Archer\/Support\/Liftoff\/Exception.html","",
                [["LaunchException","Icecave\/Archer\/Support\/Liftoff\/Exception\/LaunchException.html"," < RuntimeException",
                [        ]]        ]],["Launcher","Icecave\/Archer\/Support\/Liftoff\/Launcher.html","",
                [        ]]        ]],["Asplode","Icecave\/Archer\/Support\/Asplode.html","",
                [        ]],["Isolator","Icecave\/Archer\/Support\/Isolator.html","",
                [        ]]        ]],["Travis","Icecave\/Archer\/Travis.html","",
                [["TravisClient","Icecave\/Archer\/Travis\/TravisClient.html","",
                [        ]],["TravisConfigManager","Icecave\/Archer\/Travis\/TravisConfigManager.html","",
                [        ]]        ]]        ]]        ]]        ]

